In [14]:
# Imports and pip installations (if needed)
import pandas as pd

# Part 1: Load the dataset

In [15]:
# Load the given datasets
c = pd.read_csv('chronic_kidney_disease_categorical.csv')
n = pd.read_csv('chronic_kidney_disease_numerical.csv')

# Print the data
display(c)
display(n)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,224481,3.0,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
1,992643,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
2,308740,1.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,yes,no,ckd
3,450314,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,yes,ckd
4,881763,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,769512,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
426,872034,2.0,1.0,abnormal,abnormal,notpresent,present,yes,yes,yes,poor,no,no,ckd
427,643007,NaN,NaN,NaN,normal,notpresent,notpresent,yes,yes,yes,poor,no,no,ckd
428,840392,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,poor,no,no,ckd
429,856244,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,no,no,ckd

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,203694,38.0,80.0,99.0,19.0,0.5,147.0,3.5,13.6,44.0,7300.0,6.4
1,938027,43.0,60.0,108.0,25.0,1.0,144.0,5.0,17.8,43.0,7200.0,5.5
2,421471,37.0,60.0,111.0,35.0,0.8,135.0,4.1,16.2,50.0,5500.0,5.7
3,764115,70.0,90.0,144.0,125.0,4.0,136.0,4.6,12.0,37.0,8200.0,4.5
4,240975,47.0,80.0,95.0,35.0,0.9,140.0,4.1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
415,522912,56.0,80.0,165.0,55.0,1.8,NaN,NaN,13.5,40.0,11800.0,5.0
416,475200,64.0,100.0,163.0,54.0,7.2,140.0,4.6,7.9,26.0,7500.0,3.4
417,168242,48.0,60.0,112.0,44.0,1.2,142.0,4.9,14.5,44.0,9400.0,6.4
418,474407,21.0,90.0,107.0,40.0,1.7,125.0,3.5,8.3,23.0,12400.0,3.9
419,926033,50.0,70.0,230.0,50.0,2.2,NaN,NaN,12.0,41.0,10400.0,4.6

# Part 2: Analyze the Dataset

Refer to this: https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

Explain what the each data is in your own words. What are the features and labels? Are the features in the given datasets : categorical, numerical or both? Give 3 examples of categorical and numerical columns each (if they exist)

Answer:  
The data is perhaps the various risk-factors and charateristics of each patient, along with their status of having or not having chronic kidney disease. The features are both categorical and numerical:    
  
**Categorical features** - rbc (red blood cell), pc (puss cell), Target (chronic kidney disease or not)  
**Numerical features** - age, bp (blood pressure), bgr (blood glucose random)

# Part 3: Data Preprocessing

A fundamental skill in Machine Learning is mastering the art of data cleaning and preprocessing. In this assignment, you will learn and apply essential data cleaning techniques to transform a raw dataset into a clean, ready-to-use form which you can use for regression or classification tasks. By the end of this assignment, you'll have a fully clean dataset and a solid foundation in preparing data for various machine learning models.

## Part 3.1 : Drop Duplicate rows

Let's start by checking if the given datasets have any duplicate rows (same Unique Id). Use pandas to identify and remove these duplicate rows from the given dataset

In [16]:
# For the numerical dataset, check if there are duplicate rows in the dataset. If yes, print total number of duplicate rows
num_dupes_n = n.duplicated('unique_id').sum()
if (num_dupes_n > 0):
    print(num_dupes_n)

# Drop these duplicate rows
n = n.drop_duplicates('unique_id')

# Repeat the same for categorical dataset. Print the duplicate rows and drop them
num_dupes_c = c.duplicated('unique_id').sum()
if (num_dupes_c > 0):
    print(num_dupes_c)

c = c.drop_duplicates('unique_id')

30
30

## Part 3.2: Combine two differents datasets

A good skill to have is to know how to combine 2 different datasets.

Are all the unique ids are present in both datasets? Why do you think so? If not, what do the rows that are missing from one of the datasets look like in the combined table?

Answer:  
Not all unique ids are present in both datasets, perhaps because sufficient data for one dataset or another was not collected for some patients. When the tables are merged, if one unique id was not present in one of the databases, all of the characteristics (fields) for that database under the unique id's row will be NaN, because there was no data to put there.

In [17]:
# Merge the two given numerical and categorical datasets based on their unique_ID.
data = pd.merge(c, n, on='unique_id', how='outer')
#Print the combined dataset
display(data)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,102677,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,...,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1
1,103570,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,80.0,125.0,NaN,NaN,136.0,3.5,15.4,43.0,5600.0,4.5
2,104675,2.0,1.0,normal,normal,present,notpresent,no,yes,no,...,80.0,215.0,133.0,2.5,NaN,NaN,13.2,41.0,NaN,NaN
3,105923,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,...,90.0,139.0,89.0,3.0,140.0,4.1,12.0,37.0,7900.0,3.9
4,107297,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,70.0,NaN,NaN,NaN,NaN,NaN,16.4,43.0,10800.0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,995177,4.0,3.0,normal,abnormal,present,present,yes,yes,yes,...,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3
396,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2
397,996412,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,...,60.0,120.0,40.0,0.5,140.0,4.6,16.0,43.0,4500.0,4.9
398,997629,0.0,0.0,normal,normal,NaN,NaN,no,no,no,...,NaN,99.0,30.0,0.5,135.0,4.9,15.4,48.0,5000.0,5.2
399,997876,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,...,70.0,107.0,15.0,NaN,NaN,NaN,12.8,38.0,NaN,NaN

## Part 3.3: Rows with Missing values

Removing missing values from a dataset is important for classification because it ensures the model is trained on complete and accurate data, leading to better performance and reliable predictions. Incomplete data can introduce bias and errors, negatively impacting the model's effectiveness.

In [18]:
# Calculate the percentage of rows that contain atleast one missing value
percent_missing = (data.isna().any(axis=0).sum()) / len(data)
# Print %
print(f'%{percent_missing * 100}')
# Drop these rows from the dataset
data = data.dropna()
# Print the Dataset
display(data)

%5.75

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,102677,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,...,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1
6,109053,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,106.0,27.0,0.7,150.0,3.3,14.4,42.0,8100.0,4.7
7,114717,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,9100.0,5.2
8,118191,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,7100.0,5.3
9,118596,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,6000.0,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,980291,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,yes,no,...,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,7900.0,3.9
391,991031,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,10200.0,5.0
394,994377,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,9800.0,6.0
395,995177,4.0,3.0,normal,abnormal,present,present,yes,yes,yes,...,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3
396,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2

## Part 3.4: Sort the dataset according to the Labels

In [19]:
# Sort the dataset according to the values in 'Target' column. Make sure reset the indices after sorting
data = data.sort_values(by='Target').reset_index(drop=True)
# Print the dataset
display(data)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,102677,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,...,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1
1,337834,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,...,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
2,343710,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,9200.0,3.2
3,349892,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,10200.0,4.1
4,353025,3.0,4.0,normal,normal,notpresent,notpresent,yes,yes,no,...,70.0,253.0,150.0,11.9,132.0,5.6,10.9,31.0,8800.0,3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,5500.0,4.8
149,203466,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,7900.0,6.4
150,482105,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,7700.0,6.3
151,228849,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,6700.0,6.5
152,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2

## Part 3.5: Encoding Categorical data

In this step, we identify and process the categorical columns in the sorted dataset. We map each unique value in these columns to separate "dummy" columns.

For example, the column 'rbc' will be transformed into two columns 'rbc_normal' and 'rbc_abnormal'. If a row's value in 'rbc' is 'normal', the 'rbc_normal' column will be set to 1 and 'rbc_abnormal' will be set to 0.


**Note: Find a correct pandas function to do this **

In [20]:
# Write code here
categorical_columns = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'Target']
dummies = pd.get_dummies(data, columns=categorical_columns, drop_first=False)
data = pd.merge(data, dummies, how='left')

# Print the dataset
display(data)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,102677,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,...,True,False,False,True,False,True,False,True,True,False
1,337834,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,...,True,False,False,True,False,True,False,True,True,False
2,343710,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,False,True,False,True,False,True,True,False
3,349892,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,True,False,True,False,True,False,True,False
4,353025,3.0,4.0,normal,normal,notpresent,notpresent,yes,yes,no,...,True,False,False,True,False,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
149,203466,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
150,482105,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
151,228849,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
152,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True

In the example we went through above, another solution is to have a single column for the binary variable. In the downstream modeling would this be equivalent? What effect would this have if the categorical variable could take more than 2 values? For example, let's say we have a categorical feature that is "type of condiment" that can take 5 separate values and we are trying to predict the rating of a particular sandwich.

## Part 3.6 : Remove Outliers from Numerical Columns

Outliers can disproportionately influence the fit of a regression model, potentially leading to a model that does not generalize well therefore it is important that we remove outliers from the numerical columns of the dataset.

For this dataset, we define an outlier to be 3 times the standard deviation from the mean. Drop these outliers from the dataset

In [21]:
# Remove outliers
numerical_columns = ['age', 'bp', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc']
for col in numerical_columns:
    outlier_bound = data[col].mean() + (3 * data[col].std())
    data = data[abs(data[col]) <= outlier_bound]
# Print the dataset
display(data)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
1,337834,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,...,True,False,False,True,False,True,False,True,True,False
2,343710,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,False,True,False,True,False,True,True,False
5,397388,2.0,2.0,normal,normal,notpresent,present,yes,no,yes,...,False,True,True,False,True,False,True,False,True,False
7,438182,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,True,False,True,False,True,False,True,False
8,474407,4.0,0.0,normal,abnormal,present,present,no,no,no,...,True,False,True,False,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
149,203466,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
150,482105,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
151,228849,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
152,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True

## Part 3.7 : Normalize the Numerical Columns

Normalizing numerical attributes ensures that all features contribute equally to the model by scaling them to a consistent range, which improves model performance and convergence. It prevents features with larger scales from disproportionately influencing the model's learning process.

In [22]:
# Normalize the all Numerical Attributes in the dataset.
numeric = data[numerical_columns]
data[numerical_columns] = (numeric - numeric.min()) / (numeric.max() - numeric.min())
# Print the dataset
display(data)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
1,337834,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,...,True,False,False,True,False,True,False,True,True,False
2,343710,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,False,True,False,True,False,True,True,False
5,397388,2.0,2.0,normal,normal,notpresent,present,yes,no,yes,...,False,True,True,False,True,False,True,False,True,False
7,438182,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,...,False,True,True,False,True,False,True,False,True,False
8,474407,4.0,0.0,normal,abnormal,present,present,no,no,no,...,True,False,True,False,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,486397,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
149,203466,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
150,482105,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
151,228849,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True
152,996076,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,...,True,False,True,False,True,False,True,False,False,True

## Part 3.8: Remove Unnecessary columns

Are there any columns in this dataset which are not appropriate for modeling and predictions? Which column(s)? Justify their exclusion and remove them

Answer:  
The unique id column is not needed for modeling and predictions. It was only used to identify which parts of the data go where, thus from this point on it has no real use, as all we need is the data itself (which is already organized into separate rows).

In [23]:
#Remove that column
data = data.drop(['unique_id'], axis=1)
# Print the dataset
display(data)

,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,...,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
1,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,poor,...,True,False,False,True,False,True,False,True,True,False
2,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,poor,...,False,True,False,True,False,True,False,True,True,False
5,2.0,2.0,normal,normal,notpresent,present,yes,no,yes,good,...,False,True,True,False,True,False,True,False,True,False
7,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,...,False,True,True,False,True,False,True,False,True,False
8,4.0,0.0,normal,abnormal,present,present,no,no,no,good,...,True,False,True,False,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,...,True,False,True,False,True,False,True,False,False,True
149,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,...,True,False,True,False,True,False,True,False,False,True
150,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,...,True,False,True,False,True,False,True,False,False,True
151,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,...,True,False,True,False,True,False,True,False,False,True
152,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,...,True,False,True,False,True,False,True,False,False,True

## Part 3.9: Export the Cleaned Data

Now that you've completed these cleaning steps you should have a pandas dataframe which is much cleaner and ready for modeling. Our final step is to save our work. Export the DataFrame to a two new formats: csv and json.

In [24]:
# Export the dataframe to a new csv file
data.to_csv('chronic_kidney_disease_clean.csv', index=False)
# Export the dataframe to a new json file
data.to_json('chronic_kidney_disease_clean.json', orient='records')

# Part 4: Data conversions with Large Language Models

One powerful use case of ChatGPT (and other generative language models) is cleaning and transforming data. In some cases, these models can directly manipulate loosely structured data that you provide to them into a standard format. In the other cases, you can often prompt the model to create a conversion or extraction script for you in python or Pandas and then run it on your own. 

In this part of the assignment you will prompt 383GPT to explore these capabilities.

## Part 4.1 GPT Data Manipulation

Take the cleaned dataset that you created in part three and output the top 15 rows of that dataset. Then copy the terminal output, open 383gpt and ask it to convert that output to a markdown table. Paste that markdown table in the cell bellow

### Paste the markdown table here

| al   | su   | age       | bp   | bgr               | bu               | sc               | sod              | pot              | hemo             | pcv              | wbcc             | rbcc             | rbc_normal | pc_normal | pcc_present | ba_present | htn_yes | dm_yes | cad_yes | appet_poor | pe_yes | ane_yes | Target_notckd |
|------|------|-----------|------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|------------|-----------|-------------|------------|---------|--------|---------|-------------|--------|---------|----------------|
| 4.0  | 0.0  | 0.545454  | 0.25 | 0.201717          | 0.300654          | 0.419753          | 0.0               | 0.0               | 0.459016          | 0.421053          | 0.193548          | 0.333333          | True       | False      | True        | False      | True    | False  | False   | True        | True   | True    | False          |
| 2.0  | 0.0  | 0.714286  | 0.5  | 0.442060          | 0.901961          | 0.432099          | 0.615385          | 0.692308          | 0.172131          | 0.210526          | 0.395161          | 0.153846          | False      | False      | False       | False      | True    | True   | True    | True        | True   | False   | False          |
| 2.0  | 2.0  | 0.740260  | 1.0  | 0.901288          | 0.163399          | 0.345679          | 0.820513          | 0.256410          | 0.606557          | 0.631579          | 0.443548          | 0.410256          | True       | True       | False       | True       | True    | False  | True    | False       | False  | False   | False          |
| 2.0  | 0.0  | 0.870130  | 0.5  | 0.785408          | 0.862745          | 0.518519          | 0.692308          | 0.846154          | 0.401639          | 0.447368          | 0.233871          | 0.435897          | False      | False      | False       | False      | True    | True   | True    | False       | False  | False   | False          |
| 4.0  | 0.0  | 0.194805  | 0.75 | 0.158798          | 0.196078          | 0.160494          | 0.358974          | 0.256410          | 0.221311          | 0.184211          | 0.653226          | 0.333333          | True       | False      | True        | True       | False   | False  | False   | False       | True   | False   | False          |
| 4.0  | 2.0  | 0.753247  | 1.0  | 0.399142          | 0.287582          | 0.839506          | 0.743590          | 0.538462          | 0.188525          | 0.263158          | 0.258065          | 0.205128          | False      | False      | False       | True       | True    | True   | False   | False       | True   | False   | False          |
| 3.0  | 1.0  | 0.701299  | 0.0  | 0.935622          | 0.169935          | 0.160494          | 0.487179          | 0.128205          | 0.188525          | 0.236842          | 0.879032          | 0.102564          | True       | False      | True        | False      | True    | False  | False   | True        | False  | True    | False          |
| 2.0  | 0.0  | 0.610390  | 0.75 | 0.0               | 0.633987          | 0.839506          | 0.076923          | 0.307692          | 0.319672          | 0.342105          | 0.629032          | 0.282051          | False      | False      | True        | False      | True    | True   | False   | True        | False  | True    | False          |
| 2.0  | 0.0  | 0.649351  | 0.75 | 0.253219          | 0.633987          | 0.777778          | 0.512821          | 0.589744          | 0.286885          | 0.342105          | 0.169355          | 0.205128          | False      | False      | False       | False      | True    | False  | False   | False       | False  | False   | False          |
| 4.0  | 3.0  | 0.818182  | 0.25 | 0.618026          | 0.562092          | 0.728395          | 0.230769          | 0.358974          | 0.311475          | 0.315789          | 0.580645          | 0.179487          | True       | False      | True        | True       | True    | True   | True    | False       | True   | True    | False          |
| 1.0  | 0.0  | 0.519481  | 0.0  | 0.399142          | 0.535948          | 0.358025          | 0.769231          | 0.384615          | 0.344262          | 0.315789          | 0.830645          | 0.153846          | True       | True       | False       | False      | True    | True   | False   | False       | False  | False   | False          |
| 3.0  | 0.0  | 0.727273  | 0.25 | 0.223176          | 0.209150          | 0.160494          | 0.641026          | 0.564103          | 0.573770          | 0.605263          | 0.290323          | 0.333333          | True       | False      | False       | False      | True    | True   | False   | False       | False  | False   | False          |
| 3.0  | 1.0  | 0.636364  | 0.5  | 0.618026          | 0.411765          | 0.432099          | 0.666667          | 0.615385          | 0.434426          | 0.473684          | 0.25             | 0.282051          | True       | False      | True        | True       | True    | True   | False   | False       | True   | False   | False          |
| 4.0  | 1.0  | 0.753247  | 0.0  | 0.725322          | 0.313725          | 0.481481          | 0.666667          | 0.743590          | 0.319672          | 0.342105          | 0.258065          | 0.205128          | False      | False      | False       | True       | True    | True   | False   | True        | True   | False   | False          |
| 3.0  | 0.0  | 1.0      | 0.25 | 0.137339          | 0.326797          | 0.271605          | 0.102564          | 0.820513          | 0.254098          | 0.263158          | 0.685484          | 0.128205          | True       | True       | False       | False      | True    | False  | False   | True        | False  | True    | False          |

** Caution: ** while language models can perform data conversions they also can * hallucinate * during this process, particularly for bigger datasets. Reflect on this below, how could you mitigate data conversion hallucinations from LLM conversions?

Answer:  
From my limited understanding, LLMs primarily work through predicting/estimating what token(s) come next given the prompt/query. In other words, it is not necessarily step-by-step reading through the input query to create the table; it could possibly predict some outside data from its training set and insert it where our data should go.

The only way I could see to mitigate this is to just not rely on LLMs to do this for you, and perhaps instead ask for it to write a script to do this very thing for you, or at least help you to write it yourself (either by walking you through it or providing relevant resources).

## Part 4.2 GPT Pandas Prompting

In this section, you will prompt 383GPT to write pandas code manipulations for you.

After working with this data for awhile, we realized we're starting to forget the meanings of the abbreviated column names. Let's ask 383GPT to fix this for us. First, navigate to the [UCI dataset overview](https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease) and copy the abbrevation to name mapping. Then, go to 383GPT and instruct the LLM to provide you with a pandas script to apply this renaming to all the columns of your dataset. Paste that code below and make any adjustments necessary to run it in your notebook.

In [25]:
# Code to rename all the columns in the dataset
rename_mapping = {
    'age': 'age',  # age
    'bp': 'blood pressure',  # blood pressure
    'sg': 'specific gravity',  # specific gravity
    'al': 'albumin',  # albumin
    'su': 'sugar',  # sugar
    'rbc': 'red blood cells',  # red blood cells
    'pc': 'pus cell',  # pus cell
    'pcc': 'pus cell clumps',  # pus cell clumps
    'ba': 'bacteria',  # bacteria
    'bgr': 'blood glucose random',  # blood glucose random
    'bu': 'blood urea',  # blood urea
    'sc': 'serum creatinine',  # serum creatinine
    'sod': 'sodium',  # sodium
    'pot': 'potassium',  # potassium
    'hemo': 'hemoglobin',  # hemoglobin
    'pcv': 'packed cell volume',  # packed cell volume
    'wc': 'white blood cell count',  # white blood cell count
    'rc': 'red blood cell count',  # red blood cell count
    'htn': 'hypertension',  # hypertension
    'dm': 'diabetes mellitus',  # diabetes mellitus
    'cad': 'coronary artery disease',  # coronary artery disease
    'appet': 'appetite',  # appetite
    'pe': 'pedal edema',  # pedal edema
    'ane': 'anemia',  # anemia
    'class': 'class'  # class
}

# Rename the columns
data.rename(columns=rename_mapping, inplace=True)

## Part 4.3 Augmenting our skills with prompting

In addition, we can also use 383GPT to convert our data manipulation operations between different data manipulation languages and libraries. For example let's prompt 383GPT to convert the following SQL query to a pandas query.

**SQL Query**
```sql
SELECT Target, COUNT(*) AS count
FROM your_table_name
GROUP BY Target;
```

Prompt 383GPT to convert this to a pandas query. Run this query below, then describe what it does. (If you're not familiar with SQL that is okay you need to only comment on the final resulting output.)

In [26]:
# Converted SQL to Pandas code
result = data.groupby('Target').size().reset_index(name='count')

# Display the result
display(result)

   Target  count
0     ckd     26
1  notckd    111

The above code takes the "Target" column and counts the number of values in that column of the dataset, grouping the counts by each of the values present in that column. It returns a dataset which displays the result of counting these values.